services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
      args:
        HF_TOKEN: ${HUGGINGFACE_API_TOKEN}
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      # Required for ADC to work
      - ${GCP_SDK_CREDENTIALS_PATH}:/root/.config/gcloud/application_default_credentials.json
    env_file:
      - ../.env
    environment:
      - FIRESTORE_EMULATOR_HOST=firestore:8080
      - PYTHONUNBUFFERED=1
      # Runtime generated token for local dev
      - GCP_ID_TOKEN=${GCP_ID_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - firestore
    # uvicorn as entry point
    command: [ "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload", "--reload-dir", "src" ]

  firestore:
    image: gcr.io/google.com/cloudsdktool/google-cloud-cli:emulators
    command: gcloud beta emulators firestore start --host-port=0.0.0.0:8080
    ports:
      - "8081:8080"
